
export const posts = [
    {
        id: 1,
        user_id: 1,
        avatar:"https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg",
        name:"Nursultan",
        post_image:"https://s.rfi.fr/media/display/1842a2b4-ded1-11ec-b9fd-005056a9a7b9/w:1280/p:1x1/2022-05-28T215450Z_2063447902_UP1EI5S1OVD3R_RTRMADP_3_SOCCER-CHAMPIONS-LIV-MAD-REPORT.JPG",
        description: "manchesterunited Steppind out",
        date:"",
    },
    {
        id: 2,
        user_id: 1,
        avatar:"https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg",
        name:"Nursultan",
        post_image:"https://www.gettyimages.pt/gi-resources/images/Homepage/Hero/PT/PT_hero_42_153645159.jpg",
        description: "manchesterunited Steppind out",
        date:"",
    },
    {
        id: 3,
        user_id: 1,
        avatar:"https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg",
        name:"Nursultan",
        post_image:"https://pbs.twimg.com/media/DM6cb1kXUAIbHmD.jpg",
        description: "manchesterunited Steppind out",
        date:"",
    },
    {
        id: 4,
        user_id: 2,
        avatar:"https://h5p.org/sites/default/files/h5p/content/1209180/images/file-6113d5f8845dc.jpeg",
        name:"Aibek",
        post_image:"https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
        description: "Hello",
        date:"",
    },
    {
        id: 5,
        user_id: 2,
        avatar:"https://h5p.org/sites/default/files/h5p/content/1209180/images/file-6113d5f8845dc.jpeg",
        name:"Aibek",
        post_image:"https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
        description: "Hello",
        date:"",
    },
    {
        id: 6,
        user_id: 1,
        avatar:"https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg",
        name:"Nursultan",
        post_image:"https://thumbs.dreamstime.com/b/cosmos-beauty-deep-space-elements-image-furnished-nasa-science-fiction-art-102581846.jpg",
        description: "manchesterunited Steppind out",
        date:"",
    },
    {
        id: 7,
        user_id: 3,
        avatar:"https://www.metoffice.gov.uk/binaries/content/gallery/metofficegovuk/hero-images/advice/maps-satellite-images/satellite-image-of-globe.jpg",
        name:"Beksultan",
        post_image:"https://www.freecodecamp.org/news/content/images/2022/04/derick-mckinney-oARTWhz1ACc-unsplash.jpg",
        description: "Hi world",
        date:"",
    },
    
];

export const history = [
    {
        id: 1,
        user_id: 1,
        avatar: "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg",
        name: "Nursultan",
        story: "",
    },
    {
        id: 2,
        user_id: 2,
        avatar: "https://h5p.org/sites/default/files/h5p/content/1209180/images/file-6113d5f8845dc.jpeg",
        name: "Aibek",
        story: "",
    },
    {
        id: 3,
        user_id: 3,
        avatar: "https://www.metoffice.gov.uk/binaries/content/gallery/metofficegovuk/hero-images/advice/maps-satellite-images/satellite-image-of-globe.jpg",
        name: "Beksultan",
        story: "",
    },
    {
        id: 4,
        user_id: 3,
        avatar: "https://www.metoffice.gov.uk/binaries/content/gallery/metofficegovuk/hero-images/advice/maps-satellite-images/satellite-image-of-globe.jpg",
        name: "Beksultan",
        story: "",
    },
    {
        id: 4,
        user_id: 3,
        avatar: "https://www.metoffice.gov.uk/binaries/content/gallery/metofficegovuk/hero-images/advice/maps-satellite-images/satellite-image-of-globe.jpg",
        name: "Beksultan",
        story: "",
    },
    {
        id: 5,
        user_id: 3,
        avatar: "https://www.metoffice.gov.uk/binaries/content/gallery/metofficegovuk/hero-images/advice/maps-satellite-images/satellite-image-of-globe.jpg",
        name: "Beksultan",
        story: "",
    },
    {
        id: 6,
        user_id: 4,
        avatar: "https://www.metoffice.gov.uk/binaries/content/gallery/metofficegovuk/hero-images/advice/maps-satellite-images/satellite-image-of-globe.jpg",
        name: "Beks",
        story: "",
    },
    {
        id: 7,
        user_id: 4,
        avatar: "https://www.metoffice.gov.uk/binaries/content/gallery/metofficegovuk/hero-images/advice/maps-satellite-images/satellite-image-of-globe.jpg",
        name: "Beks",
        story: "",
    },
    {
        id: 8,
        user_id: 5,
        avatar: "https://www.metoffice.gov.uk/binaries/content/gallery/metofficegovuk/hero-images/advice/maps-satellite-images/satellite-image-of-globe.jpg",
        name: "Muhammed",
        story: "",
    },
    {
        id: 9,
        user_id: 5,
        avatar: "https://www.metoffice.gov.uk/binaries/content/gallery/metofficegovuk/hero-images/advice/maps-satellite-images/satellite-image-of-globe.jpg",
        name: "Muhammed",
    },
    {
        id: 10,
        user_id: 5,
        avatar: "https://www.metoffice.gov.uk/binaries/content/gallery/metofficegovuk/hero-images/advice/maps-satellite-images/satellite-image-of-globe.jpg",
        name: "Muhammed",
    },
    {
        id: 11,
        user_id: 6,
        avatar: "https://www.metoffice.gov.uk/binaries/content/gallery/metofficegovuk/hero-images/advice/maps-satellite-images/satellite-image-of-globe.jpg",
        name: "Bekulan",
    },
    {
        id: 12,
        user_id: 6,
        avatar: "https://www.metoffice.gov.uk/binaries/content/gallery/metofficegovuk/hero-images/advice/maps-satellite-images/satellite-image-of-globe.jpg",
        name: "Bekulan",
    },
    {
        id: 13,
        user_id: 6,
        avatar: "https://www.metoffice.gov.uk/binaries/content/gallery/metofficegovuk/hero-images/advice/maps-satellite-images/satellite-image-of-globe.jpg",
        name: "Bekulan",
    },
];

export const users = [
    {
        id:1,
        name:"Nursultan",
        avatar:"https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg",
        login:"nursultan",
        password:"12"
    },
    {
        id: 2,
        name: "Aibek",
        avatar: "https://h5p.org/sites/default/files/h5p/content/1209180/images/file-6113d5f8845dc.jpeg",
        login:"aibek",
        password:"1234"
    },
    {
        id: 3,
        name: "Beksultan",
        avatar: "https://www.metoffice.gov.uk/binaries/content/gallery/metofficegovuk/hero-images/advice/maps-satellite-images/satellite-image-of-globe.jpg",
        login:"beksultan",
        password:"123"
    },
    {
        id: 4,
        name: "Nurbolot",
        avatar: "https://tinypng.com/images/social/website.jpg",
        login:"nurba",
        password:"123456"
    }
];
export const subsc = [
    {
        id: 1,
        sub_id:2,
        user_id:1,
        follower_avatar: "https://h5p.org/sites/default/files/h5p/content/1209180/images/file-6113d5f8845dc.jpeg",
        follower_name: "Aibek",
        avatar: "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg",
        name: "Nursultan",
    },
    {
        id: 2,
        sub_id:3,
        user_id:1,
        follower_avatar: "https://www.metoffice.gov.uk/binaries/content/gallery/metofficegovuk/hero-images/advice/maps-satellite-images/satellite-image-of-globe.jpg",
        follower_name: "Beksultan",
        avatar: "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg",
        name: "Nursultan",
    },
    {
        id: 3,
        sub_id:1,
        user_id:2,
        follower_avatar: "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg",
        follower_name: "Nursultan",
        avatar: "https://h5p.org/sites/default/files/h5p/content/1209180/images/file-6113d5f8845dc.jpeg",
        name: "Aibek"
    },
    {
        id: 4,
        sub_id:3,
        user_id:2,
        follower_avatar: "https://www.metoffice.gov.uk/binaries/content/gallery/metofficegovuk/hero-images/advice/maps-satellite-images/satellite-image-of-globe.jpg",
        follower_name: "Beksultan",
        avatar: "https://h5p.org/sites/default/files/h5p/content/1209180/images/file-6113d5f8845dc.jpeg",
        name: "Aibek",
    },
    {
        id: 5,
        sub_id:1,
        user_id:3,
        follower_avatar: "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg",
        follower_name: "Nursultan",
        avatar: "https://www.metoffice.gov.uk/binaries/content/gallery/metofficegovuk/hero-images/advice/maps-satellite-images/satellite-image-of-globe.jpg",
        name: "Beksultan",
    },
    {
        id: 6,
        sub_id:2,
        user_id:3,
        follower_avatar: "https://h5p.org/sites/default/files/h5p/content/1209180/images/file-6113d5f8845dc.jpeg",
        follower_name: "Aibek",
        avatar: "https://www.metoffice.gov.uk/binaries/content/gallery/metofficegovuk/hero-images/advice/maps-satellite-images/satellite-image-of-globe.jpg",
        name: "Beksultan",
    },
    {
        id: 7,
        sub_id:1,
        user_id:4,
        follower_avatar: "https://petapixel.com/assets/uploads/2022/07/DALLEcopy.jpg",
        follower_name: "Nursultan",
        avatar: "https://tinypng.com/images/social/website.jpg",
        name: "Nurbolot",
    },
];
    
